rm default/pacotes-configuracoes.aux
rm default/aparencia-pdf-final.aux
rm default/pacotes.aux
rm informacoes-gerais.aux
rm monografia.aux
rm monografia.bbl
rm monografia.blg
rm monografia.glo
rm monografia.idx
rm monografia.lof
rm monografia.log
rm monografia.lot
rm monografia.pdf
rm monografia.toc
rm monografia.xdy
rm predefinicoes/diagramas.aux
rm predefinicoes/requisitos.aux
rm predefinicoes/casos-de-uso.aux
rm predefinicoes/gerais.aux
rm predefinicoes/cores.aux
rm tabRequisitos.aux
rm tabRequisitos2.aux
rm texto/especificacoes/avaliacoes.aux
rm texto/especificacoes/casos-de-uso.aux
rm texto/especificacoes/requisitos-nao-funcionais.aux
